//
//  BusinessHomeViewController.swift
//  BusinessSearch
//
//  Created by Christian Adiputra on 15/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit
import SkeletonView

enum TableSection: Int {
    case userList
    case loader
}

final class BusinessHomeViewController: BaseViewController {
    
    

    // MARK: - Public properties -

    var presenter: BusinessHomePresenterInterface!
    
    
    var searchText = ""
    
    
    var activityIndicator: UIActivityIndicatorView = UIActivityIndicatorView()
    
    var tableView: UITableView = {
        let tableView = UITableView()
        tableView.register(BusinessTableCell.self, forCellReuseIdentifier: "BusinessCollectionCell")
        return tableView
    }()
    
    var guideLabel: UILabel = {
        let label = UILabel()
        label.textColor = .darkGray
        label.numberOfLines = 2
        label.font = UIFont.systemFont(ofSize: 18, weight: .bold)
        label.text = "Please click search button to search restaurant"
        label.textAlignment = .center
        return label
    }()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        view.backgroundColor = .white
        configureNavBar(delegate: self, title: "")
    }
    
    private func setupView() {
        view.addSubview(tableView)
        view.addSubview(guideLabel)
        popUpDelegate = self
        tableView.delegate = self
        tableView.dataSource = self
        tableView.separatorStyle = .none
        
        tableView.snp.makeConstraints { make in
            make.right.top.bottom.left.equalToSuperview()
        }
        
        guideLabel.snp.makeConstraints { make in
            make.centerX.centerY.equalToSuperview()
            make.left.equalToSuperview().offset(16)
            make.right.equalToSuperview().offset(-16)
        }
    }
    
    
    override func viewWillAppear(_ animated: Bool) {
        tabBarController?.tabBar.isHidden = false
        tableView.reloadData()
    }
    
    func getSize() -> CGSize {
        let width = (UIScreen.main.bounds.width-40)/2
        let height = width*1.5
        return CGSize(width: width, height: height)
    }

}

// MARK: - Extensions -

extension BusinessHomeViewController: BusinessHomeViewInterface {
    func fetching() {
        self.showSpinner(onView: self.view)
    }
    
    func hideLoader() {
        self.hideBottomLoader()
    }
    
    func reloadData() {
        guideLabel.removeFromSuperview()
        DispatchQueue.main.async {
            self.removeSpinner()
            self.tableView.reloadData()
        }
    }
    
    func showAlert(message: String) {
        let alertController = UIAlertController(title: "Error", message: message, preferredStyle: .alert)

        let okAction = UIAlertAction(title: "OK", style: .default) { (_) in
            alertController.dismiss(animated: false)
            self.hideBottomLoader()
        }

        alertController.addAction(okAction)
        
        self.present(alertController, animated: true, completion: nil)
    }
    
}

extension BusinessHomeViewController: UISearchBarDelegate {
    func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
        search(shouldShow: false)
        guard let text = searchBar.text, text != "" else { return }
        searchBar.text = nil
        self.searchText = ""
    }
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        let text = searchBar.text ?? ""
        searchText = text
        presenter.searchBusiness(param: searchText)
    }
}

extension BusinessHomeViewController: UITableViewDataSource, UITableViewDelegate {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let listSection = TableSection(rawValue: section) else { return 0 }
        switch listSection {
        case .userList:
            return presenter.getTotalList()
        case .loader:
            return presenter.getTotalList() >= 20 ? 1 : 0
        }
        
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let section = TableSection(rawValue: indexPath.section) else { return UITableViewCell() }
        switch section {
        case .userList:
            guard let cell = tableView.dequeueReusableCell(withIdentifier: "BusinessCollectionCell", for: indexPath) as? BusinessTableCell else { return UITableViewCell() }
            
            let data = presenter.getBusiness(index: indexPath.row)
            DispatchQueue.main.async {
                cell.updateView(data: data)
                cell.selectionStyle = .none
            }
        case .loader:
            let cell = UITableViewCell(style: .value1, reuseIdentifier: "Cell")
            cell.textLabel?.text = "Please wait.."
            cell.textLabel?.textColor = .lightGray
            return cell
        }
        return UITableViewCell()
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 80
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        presenter.goToDetailBusiness(index: indexPath.row)
    }
    
}

extension BusinessHomeViewController {

    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        guard let section = TableSection(rawValue: indexPath.section) else { return }
        guard presenter.getTotalList() != 0 else { return }

        if section == .loader {
            print("load new data..")
            presenter.getNextPage()
        }
    }

    private func hideBottomLoader() {
        DispatchQueue.main.async {
            let lastListIndexPath = IndexPath(row: self.presenter.getTotalList() - 21, section: TableSection.userList.rawValue)
            self.tableView.scrollToRow(at: lastListIndexPath, at: .bottom, animated: true)
        }
    }
    
}

extension BusinessHomeViewController: PopUpModalDelegate {
    func didTapCancel() {
        
    }
    
    func didTapApplyFilter(filter: [Int]) {
        presenter.setFilterPrice(filter: filter)
    }
}
  
