//
//  BusinessHomeInterfaces.swift
//  BusinessSearch
//
//  Created by Christian Adiputra on 15/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit

protocol BusinessHomeWireframeInterface: WireframeInterface {
    func goToDetailBusiness(id: ListBusiness)
}

protocol BusinessHomeViewInterface: ViewInterface {
    func reloadData()
    func hideLoader()
    func fetching()
    func showAlert(message: String)
}

protocol BusinessHomePresenterInterface: PresenterInterface {
    func searchBusiness(param: String)
    func goToDetailBusiness(index: Int)
    func getTotalList() -> Int
    func getBusiness(index: Int) -> ListBusiness
    func getNextPage()
    func setFilterPrice(filter: [Int])
}

protocol BusinessHomeInteractorInterface: InteractorInterface {
    func searchBusiness(param: String)
    func getNextList()
    var listBusiness: [ListBusiness]? { get }
    var param: String? { get }
    var filterPrice: String? { get }
    var offset: Int? {
        get
    }
    func getBusiness(index: Int) -> ListBusiness
    func setFilterPrice(filter: [Int])
}

protocol BusinessHomeOutputInterface: InteractorOutputInterface {
    func didSuccessNextPage()
    func didSuccessGetData()
    func didFailedGetData(message: String)
    func didFailedGetNextPage(message: String)
}
