//
//  BusinessHomeWireframe.swift
//  BusinessSearch
//
//  Created by Christian Adiputra on 15/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit

final class BusinessHomeWireframe: BaseWireframe<BusinessHomeViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = BusinessHomeViewController()
        super.init(viewController: moduleViewController)

        let interactor = BusinessHomeInteractor()
        let presenter = BusinessHomePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }

}

// MARK: - Extensions -

extension BusinessHomeWireframe: BusinessHomeWireframeInterface {
    func goToDetailBusiness(id: ListBusiness) {
        navigationController?.pushWireframe(BusinessDetailWireframe(business: id))
    }
    
}
