//
//  BusinessHomeInteractor.swift
//  BusinessSearch
//
//  Created by Christian Adiputra on 15/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import NetworkKit

final class BusinessHomeInteractor {
    weak var presenter: BusinessHomeOutputInterface?
    
    var listBusiness: [ListBusiness]? = []
    var param: String? = ""
    var filterPrice: String? = ""
    var offset: Int? = 0
    let businessService: BusinessServiceProtocol = BusinessService()
}

// MARK: - Extensions -

extension BusinessHomeInteractor: BusinessHomeInteractorInterface {
    
    func getBusiness(index: Int) -> ListBusiness {
        guard let business = listBusiness?[index] else { return ListBusiness() }
        return business
    }
    
    func searchBusiness(param: String) {
        self.offset! = 0
        self.listBusiness?.removeAll()
        self.param = param
        guard let offset = offset else { return }
        businessService.getListBusiness(page: offset, param: param, price: filterPrice ?? "") { [weak self] response in
            guard let list = response.business else { return }
            self?.listBusiness = list
            self?.presenter?.didSuccessGetData()
        } onFailure: { [weak self] error in
            self?.presenter?.didFailedGetData(message: error)
        }
    }
    
    func getNextList() {
        self.offset! += 20
        guard let offset = offset else { return }
        businessService.getListBusiness(page: offset, param: param ?? "", price: filterPrice ?? "") { [weak self] response in
            guard let list = response.business else { return }
            self?.listBusiness?.append(contentsOf: list)
            self?.presenter?.didSuccessNextPage()
        } onFailure: { [weak self] error in
            self?.presenter?.didFailedGetNextPage(message: error)
        }
    }
    
    func setFilterPrice(filter: [Int]) {
        let stringArray = filter.map { String($0) }
        self.filterPrice = stringArray.joined(separator: ",")
    }
    
    
}
