//
//  BusinessDetailWireframe.swift
//  BusinessSearch
//
//  Created by Christian Adiputra on 19/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit

final class BusinessDetailWireframe: BaseWireframe<BusinessDetailViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(business: ListBusiness) {
        let moduleViewController = BusinessDetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = BusinessDetailInteractor()
        let presenter = BusinessDetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self, business: business)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }

}

// MARK: - Extensions -

extension BusinessDetailWireframe: BusinessDetailWireframeInterface {
    
    func goToDetailBusiness(business: ListBusiness) {
        navigationController?.presentViewWireframe(BusinessDetailWireframe(business: business))
    }
    

    
}
