//
//  BusinessDetailInterfaces.swift
//  BusinessSearch
//
//  Created by Christian Adiputra on 19/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit
protocol BusinessDetailWireframeInterface: WireframeInterface {
    func goToDetailBusiness(business: ListBusiness)
}

protocol BusinessDetailViewInterface: ViewInterface {
    func showData()
    func showReviews()
    func showAlert(message: String)
}

protocol BusinessDetailPresenterInterface: PresenterInterface {
    func fetchDetailBusiness()
    func fetchListReviews()
    func getDetail() -> ListBusiness
    func getReviews() -> [Review]
    func getReview(index: Int) -> Review
    
}

protocol BusinessDetailInteractorInterface: InteractorInterface {
    var business: ListBusiness? { get }
    var reviews: [Review]? { get }
    func getDetailBusiness(id: String)
    func getListReview(id: String)
}

protocol BusinessDetailOutputInteractorInterface: InteractorOutputInterface {
    func didSucessGetDetail()
    func didFailedGetDetail(message: String)
    func didSucessGetReviews()
    func didFailedGetReviews(message: String)
    
}
