//
//  BusinessDetailInteractor.swift
//  BusinessSearch
//
//  Created by Christian Adiputra on 19/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import NetworkKit

final class BusinessDetailInteractor {
    weak var presenter: BusinessDetailOutputInteractorInterface?
    let businessService: BusinessServiceProtocol = BusinessService()
    var business: ListBusiness?
    var reviews: [Review]?
}

// MARK: - Extensions -
extension BusinessDetailInteractor: BusinessDetailInteractorInterface {

    
    func getDetailBusiness(id: String) {
        businessService.getDetailBusiness(id: id) { [weak self] response in
            self?.business = response
            self?.presenter?.didSucessGetDetail()
        } onFailure: { [weak self] error in
            self?.presenter?.didFailedGetDetail(message: error)
        }
    }
    
    func getListReview(id: String) {
        businessService.getListReviews(id: id) { [weak self] response in
            
            self?.reviews = response.reviews
            self?.presenter?.didSucessGetReviews()
        } onFailure: { [weak self] error in
            self?.presenter?.didFailedGetReviews(message: error)
        }
    }
    
}
