//
//  BusinessDetailViewController.swift
//  BusinessSearch
//
//  Created by Christian Adiputra on 19/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit

final class BusinessDetailViewController: BaseViewController {
    
    var nameLabel: UILabel = {
        let label = UILabel()
        label.textColor = .black
        label.font = UIFont.systemFont(ofSize: 26, weight: .bold)
        label.text = "-"
        label.numberOfLines = 0
        return label
    }()
    
    var reviewLabel: UILabel = {
        let label = UILabel()
        label.textColor = .black
        label.font = UIFont.systemFont(ofSize: 14, weight: .bold)
        label.text = "Top Review"
        return label
    }()
    
    var priceLabel: PaddingLabel = {
        let label = PaddingLabel()
        label.backgroundColor = .systemGreen
        label.textColor = .white
        label.font = .systemFont(ofSize: 18, weight: .semibold)
        label.text = "-"
        label.setPadding(left: 10, right: 10, top: 8, bottom: 8)
        label.layer.cornerRadius = 12
        label.layer.masksToBounds = true
        return label
    }()
    
    var ratingLabel: PaddingLabel = {
        let label = PaddingLabel()
        label.backgroundColor = .systemGreen
        label.textColor = .white
        label.font = .systemFont(ofSize: 18, weight: .semibold)
        label.text = "⭐️ -"
        label.setPadding(left: 10, right: 10, top: 8, bottom: 8)
        label.layer.cornerRadius = 12
        label.layer.masksToBounds = true
        return label
    }()
    
    var locationBtn: UIButton = {
        let button = UIButton()
        button.backgroundColor = .systemBlue
        button.setTitle("Open location", for: .normal)
        button.titleLabel?.font = UIFont.systemFont(ofSize: 14)
        button.layer.cornerRadius = 8
        button.translatesAutoresizingMaskIntoConstraints = false
        button.addTarget(self, action: #selector(askToOpenMap), for: .touchUpInside)
        return button
    }()
    
    var imageCollectionView: UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.itemSize = CGSize(width: UIScreen.main.bounds.width - 44, height: 210)
        layout.scrollDirection = .horizontal
        let collectionView = UICollectionView(frame: CGRect.zero, collectionViewLayout: layout)
        collectionView.register(BannerCell.self, forCellWithReuseIdentifier: "BannerCell")
        collectionView.isUserInteractionEnabled = true
        collectionView.showsHorizontalScrollIndicator = false
        collectionView.isPagingEnabled = false
        return collectionView
    }()
    
    var tableView: UITableView = {
        let tableView = UITableView()
        tableView.estimatedRowHeight = 90
        tableView.backgroundColor = .lightGray
        tableView.rowHeight = UITableView.automaticDimension
        tableView.register(ReviewTableCell.self, forCellReuseIdentifier: "ReviewTableCell")
        return tableView
    }()
    
    

    // MARK: - Public properties -

    var presenter: BusinessDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        showBackButton()
        view.backgroundColor = .white
        setupView()
    }
    
    func setupView() {
        view.addSubview(nameLabel)
        view.addSubview(imageCollectionView)
        view.addSubview(priceLabel)
        view.addSubview(ratingLabel)
        view.addSubview(tableView)
        view.addSubview(reviewLabel)
        view.addSubview(locationBtn)
        imageCollectionView.delegate = self
        imageCollectionView.dataSource = self
        tableView.delegate = self
        tableView.dataSource = self
        
        nameLabel.snp.makeConstraints { make in
            make.top.equalTo(imageCollectionView.snp.bottom)
            make.left.equalToSuperview().offset(16)
            make.right.equalToSuperview().offset(-16)
        }
        
        imageCollectionView.snp.makeConstraints { make in
            make.height.equalTo(250)
            make.left.right.equalToSuperview()
            make.top.equalToSuperview().offset(topbarHeight+30)
        }
        
        priceLabel.snp.makeConstraints { make in
            make.top.equalTo(nameLabel.snp.bottom).offset(10)
            make.left.equalTo(nameLabel.snp.left)
        }
        
        ratingLabel.snp.makeConstraints { make in
            make.top.equalTo(priceLabel.snp.top)
            make.left.equalTo(priceLabel.snp.right).offset(8)
        }
        
        reviewLabel.snp.makeConstraints { make in
            make.top.equalTo(ratingLabel.snp.bottom).offset(18)
            make.left.equalTo(nameLabel.snp.left)
        }
        
        tableView.snp.makeConstraints { make in
            make.top.equalTo(reviewLabel.snp.bottom).offset(10)
            make.left.right.bottom.equalToSuperview()
        }
        
        locationBtn.snp.makeConstraints { make in
            make.right.equalToSuperview().offset(-16)
            make.centerY.equalTo(ratingLabel.snp.centerY)
            make.width.equalTo(100)
        }
    }
    
    @objc func askToOpenMap() {
        let data = presenter.getDetail()
        let latitude = data.coordinates?.getLatitude() ?? 0
        let longitude = data.coordinates?.getLongitude() ?? 0
        OpenMapDirections.present(in: self, sourceView: locationBtn, latitude: latitude, longitude: longitude, name: data.name ?? "-")
    }

}

// MARK: - Extensions -

extension BusinessDetailViewController: BusinessDetailViewInterface {
    func showAlert(message: String) {
        let alertController = UIAlertController(title: "Error", message: message, preferredStyle: .alert)

        let okAction = UIAlertAction(title: "OK", style: .default) { (_) in
            alertController.dismiss(animated: false)
        }

        alertController.addAction(okAction)
        
        self.present(alertController, animated: true, completion: nil)
    }
    
    
    
    func showData() {
        imageCollectionView.reloadData()
        let detail = presenter.getDetail()
        nameLabel.text = detail.name
        priceLabel.text = detail.price
        ratingLabel.text = "⭐️ " + detail.getRating()
    }
    
    func showReviews() {
        tableView.reloadData()
    }
    
}

extension BusinessDetailViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView,
                        layout collectionViewLayout: UICollectionViewLayout,
                        minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 8
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        let data = presenter.getDetail()
        
        return data.photos?.count ?? 1
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "BannerCell", for: indexPath) as? BannerCell else {
            return UICollectionViewCell()
        }

        let data = presenter.getDetail()
        let imageURL = data.photos?[indexPath.row] ?? ""
        cell.setupData(image: imageURL)
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {
        return UIEdgeInsets(top: 0, left: 16, bottom: 0, right: 16)
    }
    
    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        self.imageCollectionView.scrollToNearestVisibleCollectionViewCell()
    }

    func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
        if !decelerate {
            self.imageCollectionView.scrollToNearestVisibleCollectionViewCell()
        }
    }
}

extension BusinessDetailViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        let data = presenter.getReviews()
        return data.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        guard let cell = tableView.dequeueReusableCell(withIdentifier: "ReviewTableCell", for: indexPath) as? ReviewTableCell else { return UITableViewCell() }
        
        let data = presenter.getReview(index: indexPath.row)
        cell.updateView(data: data)
        cell.selectionStyle = .none
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
    
}
